In [2]:
import torch 
x = torch.arange(12)  # arange方法可以创建一个行向量x
#shape属性来访问张量（沿每个轴的长度）的形状
x.shape  # 输出：torch.Size([12])
x.numel() #输出：12，numel方法返回张量的元素总数
X = x.reshape(3, 4)  # reshape方法将x重塑为3行4列的矩阵,且可以通过-1来调用此自动计算出维度的功能
X1 = x.reshape(2, -1)  # -1表示自动计算列数
print(X1) 
print(x)  
print(X)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [3]:
torch.zeros((2, 3, 4))
torch.ones((2, 3, 4))
print(torch.zeros((2,2,2,3,4))) #可以创建一个多维张量
print(torch.ones((3, 4))) # 可以省略第一个参数，默认为1
print(torch.randn((2, 3, 4))) # 创建一个均值为0，方差为1的正态分布张量(参数全是维度)
print(torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]))#这是一个3行4列的二维张量，可以把张量理解为一个多维数组即矩阵

tensor([[[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]]],



        [[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]]]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[-0.0120, -0.9836,  1.2297, -2.1843],
         [-0.7970,  0.2024, -0.4955, -0.7310],
         [-0.1879, -0.2889, -0.2338, -0.3391]],

        [[-1.3274, -1.8751, -0.3781,  0.6526],
         

In [4]:
# 线性代数运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print (x ** y)  # 逐元素求幂运算
# 张量连结运算
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0))# dim=0表示按行连接 dim=1表示按列连接
print(torch.cat((X, Y), dim=1))
X == Y # 逐元素比较，返回布尔类型的张量

tensor([ 1.,  4., 16., 64.])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
print(X.sum()) # 求和，对所有的元素求和会得到一个单元素张量
X[-1]
X[1:3]
'''​
​不包含索引 3​​，而是遵循 ​​“左闭右开”​​ 的规则，即：
​包含起始索引 1​​
​不包含结束索引 3
'''
'''
索引和切片
'''
X[1,2]= 9  # 修改张量中指定位置的元素
X[0:2,:] = 5 # :的意思是从什么到什么，遵循左闭右开，相当于for的起点终点
print(X)  # 修改张量中指定行的所有元素
torch.mm(X, Y.T)  # 矩阵乘法，Y.T表示Y的转置

tensor(78.)
tensor([[ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 8.,  9., 10., 11.]])


tensor([[ 50.,  50.,  50.],
        [ 50.,  50.,  50.],
        [ 98., 100.,  90.]])